#!/bin/bash

# shellcheck disable=SC2016
_alias cp             'cp'        '-i'
_alias free           'free'      '-h'
_alias grep           'grep'      '--colour="auto" --group-separator="===================================" '
_alias info           'info'      '--vi-keys'
_alias ls             'ls'        '--color="auto"'
_alias mv             'mv'        '-i'
_alias pacman         'pacman'    '--color="auto"'
_alias snv            'sudoedit'
_alias systemctl      'systemctl' '--no-pager'
_alias yay            'yay'       '--color="auto"'
_alias rm             'rm'        '-i'

_alias column_color   'column' \
  '--table'                                   \
  '-C "color=blue,headercolor=reverse"'       \
  '-C "color=green,headercolor=reverse"'      \
  '-C "color=yellow,headercolor=reverse"'     \
  '-C "color=magenta,headercolor=reverse"'    \
  '-C "color=lightcyan,headercolor=reverse"'  \
  '-C "color=gray,headercolor=reverse"'
alias sudo='sudo -v; sudo '
alias D='\df -h | grep -Po "^[ ]*[/]dev[/].*" | column_color'
alias H='show_help'
alias b='cd "${BIN}"'
alias c='myfzf'
alias d='\df -h | column_color'
alias h='cd "${HOME}"'
alias l='cd_from_lf' # my lf, so it cd's shell after exiting lf
_alias B              'bat'
_alias F              'readlink'  '-f'
_alias G              'grep'      '-Pi'
_alias P              'pacman'    '--color="auto"'
_alias S              'systemctl' '--no-pager'
_alias U              'systemctl' '--user' '--no-pager'
_alias V              'viu'       # view fitted image in terminal
_alias Y              'yay'       '--color="auto"'
_alias i              'exiftool'
_alias n              'nvim'      '+":Telescope oldfiles"'
_alias p              'ps'        'ax | grep -Pi'
_alias r              'rg'        '--pcre2 -i'
_alias s              'sad'       '--pager never'
_alias t              'trash-put'
_alias v              'kitty'     'icat' # view image in terminal
_alias y              'rlwrap'    'sbcl'
_alias ii             'icl' # very cool lisp repl for terminal
_alias key            'showkey'   ' -k'
_alias gl             'glow'
_alias gse            'plocate'   '-i'  '--database="/var/lib/plocate/plocate.db" --regex'
_alias ll             'lsd'       '-l'  '--group-directories-first' '--icon="never"' '-rt' '--permission="octal"' #  --date=+" [ %_H:%M:%S | %a | %D ]" --blocks="permission,user,date,name"'
_alias lla            'lsd'       '-la' '--group-directories-first' '--icon="never"' '-rt' '--permission="octal"' '--date=+" [ %_H:%M:%S | %a | %D ]"' '--blocks="permission,user,date,name"'
_alias llg             'g'        '-la' '--time-style=+"%-2m  %-2d | %Y"' '--dir-first' '--table' '--table-style=unicode'
_alias man_search_for 'man'       '-f'
_alias man_search_in  'man'       '-K --regex'
_alias nsx            'nsxiv'     ' -a -0'
_alias nv             'nvim'
_alias nv-s           'nvim'      '+"AutoSession search"'
_alias o-rg           'source'    '"${HOME}/bin/rg_fzf.sh"'
_alias o-xdg          'xdg-open'  '"$(fzf --preview="ctpv {}")"'
_alias pac_tree 'pactree' '--color'          #Pacman Dependencies
_alias pacdep   'pacman'  '-T'               #Dependencies
_alias pacf     'pacman'  '-Fl'
_alias pacfrom  'pacman'  '-Qo'
_alias paci     'pacman'  '-Si'              #Package Info
_alias pacil    'pacman'  '-Qi'
_alias paclocal 'pacman'  '-Qm'
_alias pacneed  'pacman'  '-Qet'
_alias pacprog  'pacman'  '-F'
_alias pacse    'pacman'  '-Ss'              #Search
_alias pacsel   'pacman'  '-Qs'
_alias pgr "${PAGER}"
_alias py      'python'
_alias pyi    'ipython'
_alias ren 'renamer'
_alias se  'plocate' '-i' '--database="${LOCATE_DATABASE}" --regex'
_alias sec 'plocate'      '--database="${LOCATE_DATABASE}" --regex'
_alias szofall 'du' '-ahc  --time --max-depth=1'
_alias tracenet 'strace'
_alias tres 'ps' ' -eHo euser,ruser,suser,fuser,f,comm,label'
_alias tret 'ps' ' -ejH'
_alias yd  'yt-dlp'
_alias yda 'yt-dlp' '--extract-audio --audio-format "mp3" --output "${AUDIO:-"${HOME}/Audio"}/ytdl/%(title)s%(ext)s"'
_alias ydt 'yt-dlp' '--ignore-config --skip-download --write-subs --write-auto-subs --sub-lang en --output "$VIDEOS/transcripts/%(title)s%(ext)s"'
alias clog_builder='sbcl --eval "(ql:quickload :swank)" --eval "(asdf:load-system :clog/tools)" --eval "(clog-tools:clog-builder :port 0 :app t)"'
alias ac='          compgen -c  | grep -x'
alias ac-full='     alias_conflict --full'
alias ac-part='     alias_conflict'
alias ac-np='       alias -p | sed "s/^alias[ ]*\([^=]*\)[=][^ ][ ]*/\1\t/g" | column -t --separator '"$'\t'"
alias ac-se='       alias -p | sed "s/^alias[ ]*\([^=]*\)[=]./\1 /g" | rg --color=always -Pi'
alias ysb='         source "${HOME}/.bashrc"' # reload config
alias ex-space='    expac -HM "%m %n" | sort -n'           # Size of packages pacman
alias ex-last='     expac --timefmt="%Y %m %d %R" "%l -- %n" | sort | grep'
alias ex-opt='      expac -Qv -l "\n\t" "%n:\n\t%O"'
alias ex-dep='      expac -Qv -l "\n\t" "%n:\n\t%D"'
alias ex-pacdep='   expac -l "\n" "%D"'
alias ex-pacopt='   expac -l "\n" "%o"'
alias desk='        cd "${DESKTOP}"'
alias docs='        cd "${DOCUMENTS}"'
alias down='        cd "${DOWNLOADS}"'
alias pics='        cd "${PICTURES}"'
alias vids='        cd "${VIDEOS}"'
alias c-clone='     fzf_cd -d "${CLONED}"          -u -d1'
alias c-code='      fzf_cd -d "${CODING}"          -u -d4'
alias c-conf='      fzf_cd -d "${XDG_CONFIG_HOME}" -u -d1'
alias c-inf='       fzf_cd -d "${MY_INFORMATION}"  -u -d1'
alias vid='         open_mpv'
alias pac_all='     expac -H M "%011m\t%-20n\t%10d" $(comm -23 <(pacman -Qqen | sort) <({ pacman -Qqg xorg; expac -l "\n" "%E" base; } | sort -u)) | sort -n'
alias pacool='      pacman -Sl | grep -Fi  "[installed]" | grep -i'
alias pacnot='      pacman -Sl | grep -vFi "[installed]" | grep -i'
alias pacfiles='    list_files_pac'
alias cu='          myfzf u'
alias e-code='      fzf_open "${CODING}"'
alias e-conf='      fzf_open "${XDG_CONFIG_HOME}"'
alias copy-hist='   shellharden --syntax "${HISTFILE}" | tac |  fzf --ansi --no-preview | xclip -selection "clipboard"'
alias copy-text='   xclip -selection "clipboard" -i -r <<<'
alias copy-file='   xclip -selection "clipboard" -i -r'
alias copy-cwd='    printf "%s" "${PWD}" | xclip -selection "clipboard"'
alias copy-img='    clipboard_copy_image.sh'
alias copy-fimg='   clipboard_copy_image.sh --fzf'
alias py_heredoc='  python <<EOF'
alias ps_e='         ps -eo comm=, | grep --ignore-case'
alias ps_o='         ps -eo cmd=, | grep --ignore-case'
alias ps_t='         ps -eo pid,etimes,comm,cmd'
alias slimv_start=' rlwrap sbcl --load "${XDG_DATA_HOME}/nvim/plugged/slimv-neovim/slime/start-swank.lisp"'
alias o-nv='        fzf_edit'
alias szof='        du -axhc --time --max-depth=1 | sort -h'
alias s-bash='      grep -C "5" --file="-" -Pin "${HOME}/.bashrc" "${HOME}/.profile" "${HOME}/.bash_profile" "${HOME}/bashrc_files/"*.sh <<<'
alias s-bashf='     grep -C "5" --file="-" -Fin "${HOME}/.bashrc" "${HOME}/bashrc_files/"* <<<'
alias s-i3='        fd . -tf "${XDG_CONFIG_HOME}/i3/"   -X rg -H -u --color="always" -Pi'
alias s-nv='        fd . -tf "${XDG_CONFIG_HOME}/nvim/" -X rg -H -u --color="always" -Pi'
alias ifs_print='   printf "\n_%q_\n\n" "${IFS}"'
alias ifs_reset="   IFS=$' \t\n'"
alias tw='          taskwarrior-tui'
alias t-l='         task list'
alias t-cal="       task calendar"
alias t-proj="      task projects"
alias get_local_date_format='locale -k d_fmt'

