# vim: ft=bash:syntax=bash
#
#- ~/.bashrc
#
# shellcheck disable=SC2016,SC2064,SC1094,SC2089,SC2090

#[[ $- == *i* ]] && source "${HOME}/.local/share/blesh/ble.sh" --noattach

# If not running interactively, don't do anything
[[ $- != *i* ]] && return
# maybe above line doesn't work...
# # https://github.com/pyenv/pyenv/issues/264#issuecomment-654813922
# [[ -z "$PS1" ]] && return
# keep at top

stty -ixon #- Prevent <Ctrl-s> from being binded by terminal -#
set -o vi  #- Use VI Keys -#
umask 077  #- Default Permissions -#

#- Default PS0,PS1,PS3 if mps() doesn't run -#
PS0='\e[0 q\[\e[0m\]'
PS1=':\w/:> '
PS2=''

#export PROMPT_COMMAND='history -a'
source "${HOME}/bashrc_files/exports.sh"
source "${HOME}/bashrc_files/functions.sh"
source "${HOME}/bashrc_files/aliases.sh"
# source "${HOME}/.config/broot/launcher/bash/br"
mps 3 'r' #setting PS1
#------------------BASH-HISTORY--------#

shopt -s histappend
eval "$(zoxide init bash)"
eval "$(dircolors -b ~/.dircolors)"
eval "$(tv init bash)"
# eval "$(pyenv init - bash)"



# ---------- COMMENTED OUT ----------#
#[[ ${BLE_VERSION-} ]] && ble-attach

# export GEM_HOME="$(gem env user_gemhome)"
# export PYENV_ROOT="$HOME/.pyenv"
#
# [[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
# # Zoxide
# Zoxide

# argc-completions
#export ARGC_COMPLETIONS_ROOT="/$HOME/Desktop/CLONED/argc-completions"
#export ARGC_COMPLETIONS_PATH="$ARGC_COMPLETIONS_ROOT/completions/linux:$ARGC_COMPLETIONS_ROOT/completions"
#export PATH="${ARGC_COMPLETIONS_ROOT}/bin:$PATH"
## To add completions for only the specified command, modify next line e.g. argc_scripts=( cargo git )
#argc_scripts=( $(ls -p -1 "$ARGC_COMPLETIONS_ROOT/completions/linux" "$ARGC_COMPLETIONS_ROOT/completions" | sed -n 's/\.sh$//p') )
#source <(argc --argc-completions bash "${argc_scripts[@]}")


activate_conda() {
  __conda_setup="$('/$HOME/.local/share/miniconda/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
  if [ $? -eq 0 ]; then
      eval "$__conda_setup"
  else
      if [ -f "/$HOME/.local/share/miniconda/etc/profile.d/conda.sh" ]; then
          . "/$HOME/.local/share/miniconda/etc/profile.d/conda.sh"
      else
          export PATH="/$HOME/.local/share/miniconda/bin:$PATH"
      fi
  fi
  unset __conda_setup
  # <<< conda initialize <<<
}
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
if [[ "${MY_CONDA}" -eq 1 ]] ; then
  __conda_setup="$('/$HOME/.local/share/miniconda/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
  if [ $? -eq 0 ]; then
      eval "$__conda_setup"
  else
      if [ -f "/$HOME/.local/share/miniconda/etc/profile.d/conda.sh" ]; then
          . "/$HOME/.local/share/miniconda/etc/profile.d/conda.sh"
      else
          export PATH="/$HOME/.local/share/miniconda/bin:$PATH"
      fi
  fi
  unset __conda_setup
  # <<< conda initialize <<<
fi
