#!/usr/bin/bash

#set forceueberzug
#set forcechafa
#set forcekitty
#set chafasixel
set shell "/usr/bin/bash"

preview my_epub .epub {{
    a="$((w*h))"
    [[ "${a}" -gt 500 ]] && a="500"
    gnome-epub-thumbnailer -s "${a}" "${f}" "${cache_f}.png"
    setup_image
    send_image "${cache_f}.png"
}}

preview mygzip .gz {{
    zcat "${f}"
}}

preview pygm .log {{
    pygmentize "${f}"
}}

preview myjs .js .json .html {{
    highlight "${f}" --stdout --out-format="ansi"
}}

preview mylua .lua {{
    highlight "${f}" --stdout --out-format="ansi"
}}

