#!/usr/bin/bash

#set forceueberzug
set shell "/usr/bin/bash"

preview myepub .epub {{
    gname="/tmp/gnome_epub_$(date +%9N).png"
    a="$((w*h))"
    [[ "${a}" -gt 500 ]] && a="500"
    gnome-epub-thumbnailer -s "${a}" "${f}" "${gname}"
    setup_image
    send_image "${gname}"
}}

