local my_plugins = {
["luasnip"                     ]  = { 'L3MON4D3',           'LuaSnip'                       },
["cmp lsp"                     ]  = { 'hrsh7th',            'cmp-nvim-lsp'                  },
["cmp lua"                     ]  = { 'hrsh7th',            'cmp-nvim-lua'                  },
["cmp buffer"                  ]  = { 'hrsh7th',            'cmp-buffer'                    },
["cmp cmdline"                 ]  = { 'hrsh7th',            'cmp-cmdline'                   },
["cmp env"                     ]  = { 'SergioRibera',       'cmp-dotenv'                    },
["cmp luasnip"                 ]  = { 'saadparwaiz1',       'cmp_luasnip'                   },
["cmp path"                    ]  = { 'hrsh7th',            'cmp-path'                      },
["cmp auto hint"               ]  = { 'hrsh7th',            'cmp-nvim-lsp-signature-help'   },
['cmp plain english'           ]  = { 'uga-rosa',           'cmp-dictionary'                },
['cmp nvim tags'               ]  = { 'quangnguyen30192',   'cmp-nvim-tags'                 },
['cmp ctags'                   ]  = { 'delphinus',          'cmp-ctags'                     },
["vlime cmp"                   ]  = { 'HiPhish',            'nvim-cmp-vlime'                },
["nvim cmp"                    ]  = { 'hrsh7th',            'nvim-cmp'                      },
["devicons"                    ]  = { 'nvim-tree',          'nvim-web-devicons'             },
["plenary"                     ]  = { 'nvim-lua',           'plenary.nvim'                  },
["elixir"                      ]  = { 'elixir-tools',       'elixir-tools.nvim'             },
["elixirfiledetect"            ]  = { 'elixir-editors',     'vim-elixir'                    },
["floatterm"                   ]  = { 'voldikss',           'vim-floaterm'                  },
["fzf"                         ]  = { 'junegunn',           'fzf.vim'                       },
["git"                         ]  = { 'lewis6991',          'gitsigns.nvim'                 },
["lf"                          ]  = { 'ptzz',               'lf.vim'                        },
['lisp autoformat'             ]  = { 'vim-autoformat',     'vim-autoformat'                },
["lisp paredit"                ]  = { 'vim-scripts',        'paredit.vim'                   },
["lisp vlime"                  ]  = { 'vlime',              'vlime',                        { ['rtp']= 'vim/'} },
["live preview html"           ]  = { 'turbio',             'bracey.vim',                   { ['do'] = 'npm install --prefix server'} },
["lspconfig"                   ]  = { 'neovim',             'nvim-lspconfig'                },
["lsp lines"                   ]  = { 'maan2003',           'lsp_lines.nvim'                },
["lsp saga"                    ]  = { 'nvimdev',            'lspsaga.nvim'                  },
["lsp statusline"              ]  = { 'nvim-lua',           'lsp-status.nvim'               },
["markdown preview"            ]  = { 'iamcco',             'markdown-preview.nvim',        { ['do'] = 'cd app && yarn install' } },
["marks"                       ]  = { 'chentoast',          'marks.nvim'                    },
["neoterm"                     ]  = { 'kassio',             'neoterm'                       },
["nui"                         ]  = { 'MunifTanjim',        'nui.nvim'                      },
["restore view"                ]  = { 'vim-scripts',        'restore_view.vim'              },
["show key hints"              ]  = { 'folke',              'which-key.nvim'                },
["tokyonight"                  ]  = { 'folke',              'tokyonight.nvim'               },
["treesitter"                  ]  = { 'nvim-treesitter',    'nvim-treesitter',              {['do']= ':TSUpdate'} },
["treesitter-extra"            ]  = { 'nvim-treesitter',    'nvim-treesitter-textobjects'   },
['luarocks for nvim'           ]  = { 'theHamsta',          'nvim_rocks',                   {['do']= 'pipx install hererocks && python3 -mhererocks . -j2.1.0-beta3 -r3.0.0 && cp nvim_rocks.lua lua'}},
['vim latex'                   ]  = { 'lervag',             'vimtex'                        },
['vim latex snips for vimtex'  ]  = { 'micangl',            'cmp-vimtex'                    },
['Sidebar file explorer'       ]  = { 'preservim',          'nerdtree'                      },
['i3 syntax'                   ]  = { 'PotatoesMaster',     'i3-vim-syntax'                 },
['lf file manager syntax'      ]  = { 'VebbNix',            'lf-vim'                        },
['kitty syntax'                ]  = { 'fladson',            'vim-kitty',                    { ['tag']= '*' } },
['PlantUML Syntax'             ]  = { 'aklt',               'plantuml-syntax'               },
['markdown Syntax'             ]  = { 'drmingdrmer',        'vim-syntax-markdown'           },
['move file'                   ]  = { 'kovetskiy',          'neovim-move',                  { ['do'] = ':UpdateRemotePlugins' } },
['code-action previews'        ]  = { 'aznhe21',            'actions-preview.nvim'          },
['auto session'                ]  = { 'rmagatti',           'auto-session'                  } }


