#!/bin/bash
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

export            MYPRINTER="MYPRINT"
export           NNN_COPIER="$HOME/nscript/csript"
export                 DOCS="$HOME/Documents/"
export                 DESK="$HOME/Desktop/"
export                 DOWN="$HOME/Downloads/"
export              MYSTUFF="$HOME/Documents/MyStuff/"
export               EDITOR="nvim"
export             NVIMSWAP="$HOME/.local/share/nvim/swap/"
#export           PYTHONPATH="$PYTHONPATH:/home/maceurt/MY_PYTHON_MODULES/"
#export           PYTHONPATH="$PYTHONPATH:/usr/bin/python3"
export           AUTOBACKUP="/mnt/ed3/"
export QT_QPA_PLATFORMTHEME=qt5ct
export      FZF_CTRL_T_OPTS="--preview '(highlight -O ansi -l {} 2> /dev/null || cat {} || tree -C {}) 2> /dev/null | head -200'"
export			       LESS=""
export				   PATH="/usr/bin/:${PATH}"
#export 				   LESS='-R --use-color -Dd+r$Du+b'
#export 				   PAGER='w3m -o display_lineinfo=TRUE'
export				   TERM=st
export		XDG_CONFIG_HOME="$HOME/.config"
export QT_QPA_PLATFORMTHEME="qt5ct"
. $HOME/.secrets ####-!!-!!-!!-IGNORE-!!-!!-!!-####
userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

SESSION=${1:-i3wm}

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

get_session(){
	local dbus_args=(--sh-syntax --exit-with-session)
	case "$1" in
		awesome) dbus_args+=(awesome) ;;
		bspwm) dbus_args+=(bspwm-session) ;;
		budgie) dbus_args+=(budgie-desktop) ;;
		cinnamon) dbus_args+=(cinnamon-session) ;;
		deepin) dbus_args+=(startdde) ;;
		enlightenment) dbus_args+=(enlightenment_start) ;;
		fluxbox) dbus_args+=(startfluxbox) ;;
		gnome) dbus_args+=(gnome-session) ;;
		i3|i3wm) dbus_args+=(i3 --shmlog-size 0) ;;
		jwm) dbus_args+=(jwm) ;;
		kde) dbus_args+=(startplasma-x11) ;;
		lxde) dbus_args+=(startlxde) ;;
		lxqt) dbus_args+=(lxqt-session) ;;
		mate) dbus_args+=(mate-session) ;;
		xfce) dbus_args+=(xfce4-session) ;;
		openbox) dbus_args+=(openbox-session) ;;
		*) dbus_args+=("$1") ;;
	esac

	echo "dbus-launch ${dbus_args[*]}"
}

A="$(xrandr | grep -Po  'HDMI[^ ]+')"
B="$(xrandr | grep -Po  'DVI[^ ]+')"
            
xset -dpms
xset s off
xset r rate 200 40
##### This turns off mouse acceleration 
xinput --set-prop 12   "libinput Accel Speed" -1
##### Increases mouse speed, neccesary to adjust this value if you do not want mouse acceleration.
xinput --set-prop 12   "Coordinate Transformation Matrix" 1, 0, 0, 0, 1, 0, 0, 0, 0.44
xmodmap -e             "keycode 49  = 0x0000 0xffeb 0x0000 0xffeb" 
xmodmap -e 	       	   "keycode 133 = 0x007e 0x0060 0x007e 0x0060" 
xrandr --output "${A}" --left-of "${B}"
xrandr --output "${B}" --primary
deluged
exec $(get_session "${SESSION}")


