#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

. "${HOME}/.secrets"

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi


xset -dpms
xset s off
xset r rate 200 40
##### This turns off mouse acceleration
xinput --set-prop 12   "libinput Accel Speed" -1
##### Increases mouse speed, neccesary to adjust this value if you do not want mouse acceleration.
xinput --set-prop 12    "Coordinate Transformation Matrix" 1, 0, 0, 0, 1, 0, 0, 0, 0.44
xmodmap -e              "keycode 49  = 0x0000 0xffeb 0x0000 0xffeb"
xmodmap -e              "keycode 133 = 0x007e 0x0060 0x007e 0x0060"
. "${HOME}/.secret_xinit"

exec /usr/bin/i3


